### ISSUE TITLE
Just a little correction. A parameter changed in script.

### ISSUE THREAD

**Issue by shogi880** [kzl/decision-transformer#11]
Thanks for your exciting work!!!

The example usage of Atari.
It will work when use `--context_length 30` instead of `--block_size 90 `

`python run_dt_atari.py --seed 123 --block_size 90 --epochs 5 --model_type 'reward_conditioned' --num_steps 500000 --num_buffers 50 --game 'Breakout' --batch_size 128 --data_dir_prefix [DIRECTORY_NAME]`
>>
`python run_dt_atari.py --seed 123  --context_length 30 --epochs 5 --model_type 'reward_conditioned' --num_steps 500000 --num_buffers 50 --game 'Breakout' --batch_size 128 --data_dir_prefix [DIRECTORY_NAME]`

**Comment by lili-chen** [comment]
Yes sorry about that, we fixed it in a recent commit so you might have pulled before the update!
