### ISSUE TITLE
Application to multi-agent environment 

### ISSUE THREAD

**Issue by skull8888888** [kzl/decision-transformer#14]
Thank you for your great work!

I was wondering if this method can be applied to the environment with multiple agents, something like [this](https://www.kaggle.com/c/hungry-geese/overview). I am just starting in reinforcement learning and for now I see no reason why it couldn't be applied. But, maybe you thought about it?

**Comment by kzl** [comment]
Yes, there should not be any fundamental limitation when trying to apply to multi-agent environments.
