### ISSUE TITLE
how to get the score of an expert policy and some other details

### ISSUE THREAD

**Issue by TianhongDai** [kzl/decision-transformer#16]
Hi,

Thanks for sharing this interesting work. However, I have few questions in the paper:

1) Could I know how to get the score of an expert policy that you used to normalize the score in Tables? If possible, could you share these information, please?

2) When you report the results in the paper (e.g., Table 4), which score do you use -  the score in the last epoch or the best score during training?

Looking forward to your reply!

Best Wishes

**Comment by kzl** [comment]
1. For Atari, see Table 11 in Appendix B. For D4RL, see the benchmarking paper, also located [here](https://github.com/rail-berkeley/d4rl/blob/master/d4rl/infos.py).
2. We use the last epoch, although we found this was not significant (in contrast, TD learning algorithms tend to be very sensitive to this).
