### ISSUE TITLE
Timesteps Shape

### ISSUE THREAD

**Issue by MrShininnnnn** [kzl/decision-transformer#19]
Hi there,

Thanks for the code sharing and I'm trying to go through the paper with the help of the code.

When initializing the dataset, I find that timesteps are selected with [idx:idx+1] on line 64 in run_dt_atari.py, resulting in a shape of (batch_size, 1) instead of the comment on line 225 in model_atari.py (batch_size, block_size, 1). 

Please help to confirm the shape of timesteps and whether there is an error regarding the timesteps selection.

**Comment by lili-chen** [comment]
Yes there is a mistake in the comment on line 225, since you only need the timestep for the first element in the block. We'll fix it soon, thanks for the catch! In general, we found the details of the position embedding to not make much of a difference in the results.
