### ISSUE TITLE
Do both BC and DT fit the training data well?

### ISSUE THREAD

**Issue by w-hc** [kzl/decision-transformer#2]
Hi thanks for the interesting work!
A question here: how well do Behavior Cloning and Decision Transformer fit the training data (esp. when there is a mixture of policies, like the ones with replay data or medium + expert)? This doesn't seem to be reported in the paper. Do they fit the data (roughly) equally well?

**Comment by kzl** [comment]
Thanks for the question! I've attached some of the L2 losses for both. In short Decision Transformer fits the training data better across all datasets (a combination of return conditioning and longer context length).

![image](https://user-images.githubusercontent.com/23283372/120881118-bf8cde80-c583-11eb-82e8-83f96dabe387.png)
