### ISSUE TITLE
Regarding atari breakout results

### ISSUE THREAD

**Issue by dido1998** [kzl/decision-transformer#21]
Hi,

Thanks for sharing the implementation. I am unable to reproduce the performance reported in the paper for breakout. I ran this script: https://github.com/kzl/decision-transformer/blob/master/atari/run.sh. I get an eval return of 42 as compared to 267.5 reported in table 4 of that paper. Am I missing something?

Thanks

**Comment by lili-chen** [comment]
The 267.5 is a normalized score, which corresponds to a raw score somewhere in the 70s. The reason you're getting 42 and not in the 70s is probably due to the somewhat large variance between seeds.
