### ISSUE TITLE
Minor bug that removes best performing trajectory in gym experiments

### ISSUE THREAD

**Issue by micahcarroll** [kzl/decision-transformer#33]
I believe that this line should have a `<=` rather than a `<` in order for the code to not cut out the best performing trajectory even when using `pct_traj = 1.`

https://github.com/kzl/decision-transformer/blob/f04280e3668a992c41b38bdfb6b6181d61b4dc52/gym/experiment.py#L109

To replicate, use a dataset with 2 trajectories and use `pct_traj = 1.` and the resulting `num_trajectories` will just be 1 rather than 2.

**Comment by kzl** [comment]
Thanks for catching this! I think you're right.
