### ISSUE TITLE
Atari results

### ISSUE THREAD

**Issue by TongZhangTHU** [kzl/decision-transformer#46]
Hi,

Thanks for your wonderful work. I cannot reproduce the performance reported in the paper for Atari.  For example, compared to Table 1,  my normalized score for Breakout is 147.738, for Seaquest is 1.875 (averaged over 3 seeds, I use the same seed as this script: [https://github.com/kzl/decision-transformer/blob/master/atari/run.sh](https://github.com/kzl/decision-transformer/blob/master/atari/run.sh) ) I wonder did you use the same seeds (123, 231, 312) as that script ? Or did I miss something?

**Comment by GilgameshD** [comment]
A follow-up question. How to normalize the score?

**Comment by TongZhangTHU** [comment]
@GilgameshD normalized score =100 * (score - random score)/(expert score - random score)

**Comment by lili-chen** [comment]
Hi, I did use those seeds but I’ve realized that there is some additional stochasticity that I have not been able to locate. Really sorry about that!

**Comment by yiyeChen** [comment]
@TongZhangTHU 
Another follow up question, where to find random score and expert score? I did find a table from [here](https://github.com/Kaixhin/Atari/blob/master/Evaluator.lua) but not sure if everyone is using the same set of parameters.
