### ISSUE TITLE
Any reason for using different models for gym and atari experiments?

### ISSUE THREAD

**Issue by GilgameshD** [kzl/decision-transformer#47]
I am wondering if there is any reason for using different code bases and model structures for these two experiments. I am trying to use DT for other environments but not sure which version I should use. Thanks.

**Comment by shahaamirbader** [comment]
This seems to be a valid question, closed without response.

**Comment by pwyq** [comment]
I think because gym model is for continuous action spaces, while atari model is for discrete action spaces
