### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by yuanmao** [kzl/decision-transformer#6]
Hi team,

Nice work! 

Not sure if it affects performance at all, but I was wondering why you are assigning actions to stepwise_returns here? 

https://github.com/kzl/decision-transformer/blob/4597fba9a3f6cffb26926d0bb570d85187eb3b16/atari/create_dataset.py#L68

**Comment by lili-chen** [comment]
Thanks for the catch! We'll fix the bug. It doesn't affect performance on the 1% dataset.
