### ISSUE TITLE
MultiDiscrete Action Space

### ISSUE THREAD

**Issue by hamzaali98** [kzl/decision-transformer#71]
I am working with this gym environment [mobile-env](https://github.com/stefanbschneider/mobile-env) which has a MultiDiscrete Action Space. I am wondering is there a way we can change the way we can use the gym implementation which produces an array of continuous outputs into a MultiDiscrete output? 

Any sort of help/suggestion would be appreciated! :)

**Comment by kzl** [comment]
Hi, the simplest way to do this is probably to just expand the output dim of the action by a bunch, and then reshape the output predictions into the shape you need. You can also replace the loss function for training to match.

Alternatively, you could add multiple action tokens, one for each dimension of your action space.
