### ISSUE TITLE
Getting killed before loading any data

### ISSUE THREAD

**Issue by YashButala** [kzl/decision-transformer#9]
Getting the following output:

```
Loading from buffer 45 which has 0 already loaded
Killed

```
Probably error in this line:
https://github.com/kzl/decision-transformer/blob/c9e6ac0b75895cef3e7c06cd309fd398ec9ceef5/atari/fixed_replay_buffer.py#L54

Memory seems sufficient. What could be the reason?

Thanking you.

**Comment by SunHaoOne** [comment]
[Maybe this will help you.](https://github.com/kzl/decision-transformer/issues/8) 
I have changed the `replay_capacity=100000` and `trajectories_per_buffer=10`
